// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: urlo/v1/service.proto

package urlov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kongken/urlo/pkg/proto/urlo/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UrlServiceName is the fully-qualified name of the UrlService service.
	UrlServiceName = "urlo.v1.UrlService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UrlServiceShortenProcedure is the fully-qualified name of the UrlService's Shorten RPC.
	UrlServiceShortenProcedure = "/urlo.v1.UrlService/Shorten"
	// UrlServiceResolveProcedure is the fully-qualified name of the UrlService's Resolve RPC.
	UrlServiceResolveProcedure = "/urlo.v1.UrlService/Resolve"
	// UrlServiceGetStatsProcedure is the fully-qualified name of the UrlService's GetStats RPC.
	UrlServiceGetStatsProcedure = "/urlo.v1.UrlService/GetStats"
	// UrlServiceDeleteProcedure is the fully-qualified name of the UrlService's Delete RPC.
	UrlServiceDeleteProcedure = "/urlo.v1.UrlService/Delete"
	// UrlServiceListClicksProcedure is the fully-qualified name of the UrlService's ListClicks RPC.
	UrlServiceListClicksProcedure = "/urlo.v1.UrlService/ListClicks"
)

// UrlServiceClient is a client for the urlo.v1.UrlService service.
type UrlServiceClient interface {
	Shorten(context.Context, *connect.Request[v1.ShortenRequest]) (*connect.Response[v1.ShortenResponse], error)
	Resolve(context.Context, *connect.Request[v1.ResolveRequest]) (*connect.Response[v1.ResolveResponse], error)
	GetStats(context.Context, *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error)
	Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error)
	// ListClicks returns recent click events for a short link, newest first.
	ListClicks(context.Context, *connect.Request[v1.ListClicksRequest]) (*connect.Response[v1.ListClicksResponse], error)
}

// NewUrlServiceClient constructs a client for the urlo.v1.UrlService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUrlServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UrlServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	urlServiceMethods := v1.File_urlo_v1_service_proto.Services().ByName("UrlService").Methods()
	return &urlServiceClient{
		shorten: connect.NewClient[v1.ShortenRequest, v1.ShortenResponse](
			httpClient,
			baseURL+UrlServiceShortenProcedure,
			connect.WithSchema(urlServiceMethods.ByName("Shorten")),
			connect.WithClientOptions(opts...),
		),
		resolve: connect.NewClient[v1.ResolveRequest, v1.ResolveResponse](
			httpClient,
			baseURL+UrlServiceResolveProcedure,
			connect.WithSchema(urlServiceMethods.ByName("Resolve")),
			connect.WithClientOptions(opts...),
		),
		getStats: connect.NewClient[v1.GetStatsRequest, v1.GetStatsResponse](
			httpClient,
			baseURL+UrlServiceGetStatsProcedure,
			connect.WithSchema(urlServiceMethods.ByName("GetStats")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.DeleteRequest, v1.DeleteResponse](
			httpClient,
			baseURL+UrlServiceDeleteProcedure,
			connect.WithSchema(urlServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		listClicks: connect.NewClient[v1.ListClicksRequest, v1.ListClicksResponse](
			httpClient,
			baseURL+UrlServiceListClicksProcedure,
			connect.WithSchema(urlServiceMethods.ByName("ListClicks")),
			connect.WithClientOptions(opts...),
		),
	}
}

// urlServiceClient implements UrlServiceClient.
type urlServiceClient struct {
	shorten    *connect.Client[v1.ShortenRequest, v1.ShortenResponse]
	resolve    *connect.Client[v1.ResolveRequest, v1.ResolveResponse]
	getStats   *connect.Client[v1.GetStatsRequest, v1.GetStatsResponse]
	delete     *connect.Client[v1.DeleteRequest, v1.DeleteResponse]
	listClicks *connect.Client[v1.ListClicksRequest, v1.ListClicksResponse]
}

// Shorten calls urlo.v1.UrlService.Shorten.
func (c *urlServiceClient) Shorten(ctx context.Context, req *connect.Request[v1.ShortenRequest]) (*connect.Response[v1.ShortenResponse], error) {
	return c.shorten.CallUnary(ctx, req)
}

// Resolve calls urlo.v1.UrlService.Resolve.
func (c *urlServiceClient) Resolve(ctx context.Context, req *connect.Request[v1.ResolveRequest]) (*connect.Response[v1.ResolveResponse], error) {
	return c.resolve.CallUnary(ctx, req)
}

// GetStats calls urlo.v1.UrlService.GetStats.
func (c *urlServiceClient) GetStats(ctx context.Context, req *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error) {
	return c.getStats.CallUnary(ctx, req)
}

// Delete calls urlo.v1.UrlService.Delete.
func (c *urlServiceClient) Delete(ctx context.Context, req *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// ListClicks calls urlo.v1.UrlService.ListClicks.
func (c *urlServiceClient) ListClicks(ctx context.Context, req *connect.Request[v1.ListClicksRequest]) (*connect.Response[v1.ListClicksResponse], error) {
	return c.listClicks.CallUnary(ctx, req)
}

// UrlServiceHandler is an implementation of the urlo.v1.UrlService service.
type UrlServiceHandler interface {
	Shorten(context.Context, *connect.Request[v1.ShortenRequest]) (*connect.Response[v1.ShortenResponse], error)
	Resolve(context.Context, *connect.Request[v1.ResolveRequest]) (*connect.Response[v1.ResolveResponse], error)
	GetStats(context.Context, *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error)
	Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error)
	// ListClicks returns recent click events for a short link, newest first.
	ListClicks(context.Context, *connect.Request[v1.ListClicksRequest]) (*connect.Response[v1.ListClicksResponse], error)
}

// NewUrlServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUrlServiceHandler(svc UrlServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	urlServiceMethods := v1.File_urlo_v1_service_proto.Services().ByName("UrlService").Methods()
	urlServiceShortenHandler := connect.NewUnaryHandler(
		UrlServiceShortenProcedure,
		svc.Shorten,
		connect.WithSchema(urlServiceMethods.ByName("Shorten")),
		connect.WithHandlerOptions(opts...),
	)
	urlServiceResolveHandler := connect.NewUnaryHandler(
		UrlServiceResolveProcedure,
		svc.Resolve,
		connect.WithSchema(urlServiceMethods.ByName("Resolve")),
		connect.WithHandlerOptions(opts...),
	)
	urlServiceGetStatsHandler := connect.NewUnaryHandler(
		UrlServiceGetStatsProcedure,
		svc.GetStats,
		connect.WithSchema(urlServiceMethods.ByName("GetStats")),
		connect.WithHandlerOptions(opts...),
	)
	urlServiceDeleteHandler := connect.NewUnaryHandler(
		UrlServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(urlServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	urlServiceListClicksHandler := connect.NewUnaryHandler(
		UrlServiceListClicksProcedure,
		svc.ListClicks,
		connect.WithSchema(urlServiceMethods.ByName("ListClicks")),
		connect.WithHandlerOptions(opts...),
	)
	return "/urlo.v1.UrlService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UrlServiceShortenProcedure:
			urlServiceShortenHandler.ServeHTTP(w, r)
		case UrlServiceResolveProcedure:
			urlServiceResolveHandler.ServeHTTP(w, r)
		case UrlServiceGetStatsProcedure:
			urlServiceGetStatsHandler.ServeHTTP(w, r)
		case UrlServiceDeleteProcedure:
			urlServiceDeleteHandler.ServeHTTP(w, r)
		case UrlServiceListClicksProcedure:
			urlServiceListClicksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUrlServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUrlServiceHandler struct{}

func (UnimplementedUrlServiceHandler) Shorten(context.Context, *connect.Request[v1.ShortenRequest]) (*connect.Response[v1.ShortenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("urlo.v1.UrlService.Shorten is not implemented"))
}

func (UnimplementedUrlServiceHandler) Resolve(context.Context, *connect.Request[v1.ResolveRequest]) (*connect.Response[v1.ResolveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("urlo.v1.UrlService.Resolve is not implemented"))
}

func (UnimplementedUrlServiceHandler) GetStats(context.Context, *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("urlo.v1.UrlService.GetStats is not implemented"))
}

func (UnimplementedUrlServiceHandler) Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("urlo.v1.UrlService.Delete is not implemented"))
}

func (UnimplementedUrlServiceHandler) ListClicks(context.Context, *connect.Request[v1.ListClicksRequest]) (*connect.Response[v1.ListClicksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("urlo.v1.UrlService.ListClicks is not implemented"))
}
