// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: urlo/v1/service.proto

package urlov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_urlo_v1_service_proto protoreflect.FileDescriptor

const file_urlo_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15urlo/v1/service.proto\x12\aurlo.v1\x1a\x11urlo/v1/url.proto2\x84\x02\n" +
	"\n" +
	"UrlService\x12<\n" +
	"\aShorten\x12\x17.urlo.v1.ShortenRequest\x1a\x18.urlo.v1.ShortenResponse\x12<\n" +
	"\aResolve\x12\x17.urlo.v1.ResolveRequest\x1a\x18.urlo.v1.ResolveResponse\x12?\n" +
	"\bGetStats\x12\x18.urlo.v1.GetStatsRequest\x1a\x19.urlo.v1.GetStatsResponse\x129\n" +
	"\x06Delete\x12\x16.urlo.v1.DeleteRequest\x1a\x17.urlo.v1.DeleteResponseB2Z0github.com/kongken/urlo/pkg/proto/urlo/v1;urlov1b\x06proto3"

var file_urlo_v1_service_proto_goTypes = []any{
	(*ShortenRequest)(nil),   // 0: urlo.v1.ShortenRequest
	(*ResolveRequest)(nil),   // 1: urlo.v1.ResolveRequest
	(*GetStatsRequest)(nil),  // 2: urlo.v1.GetStatsRequest
	(*DeleteRequest)(nil),    // 3: urlo.v1.DeleteRequest
	(*ShortenResponse)(nil),  // 4: urlo.v1.ShortenResponse
	(*ResolveResponse)(nil),  // 5: urlo.v1.ResolveResponse
	(*GetStatsResponse)(nil), // 6: urlo.v1.GetStatsResponse
	(*DeleteResponse)(nil),   // 7: urlo.v1.DeleteResponse
}
var file_urlo_v1_service_proto_depIdxs = []int32{
	0, // 0: urlo.v1.UrlService.Shorten:input_type -> urlo.v1.ShortenRequest
	1, // 1: urlo.v1.UrlService.Resolve:input_type -> urlo.v1.ResolveRequest
	2, // 2: urlo.v1.UrlService.GetStats:input_type -> urlo.v1.GetStatsRequest
	3, // 3: urlo.v1.UrlService.Delete:input_type -> urlo.v1.DeleteRequest
	4, // 4: urlo.v1.UrlService.Shorten:output_type -> urlo.v1.ShortenResponse
	5, // 5: urlo.v1.UrlService.Resolve:output_type -> urlo.v1.ResolveResponse
	6, // 6: urlo.v1.UrlService.GetStats:output_type -> urlo.v1.GetStatsResponse
	7, // 7: urlo.v1.UrlService.Delete:output_type -> urlo.v1.DeleteResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_urlo_v1_service_proto_init() }
func file_urlo_v1_service_proto_init() {
	if File_urlo_v1_service_proto != nil {
		return
	}
	file_urlo_v1_url_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_urlo_v1_service_proto_rawDesc), len(file_urlo_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_urlo_v1_service_proto_goTypes,
		DependencyIndexes: file_urlo_v1_service_proto_depIdxs,
	}.Build()
	File_urlo_v1_service_proto = out.File
	file_urlo_v1_service_proto_goTypes = nil
	file_urlo_v1_service_proto_depIdxs = nil
}
