// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: urlo/v1/url.proto

package urlov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortLink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Short code, e.g. "abc123".
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Original long URL.
	LongUrl string `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	// Fully-qualified short URL, e.g. "https://urlo.example/abc123".
	ShortUrl  string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Optional expiration time. Zero means no expiration.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	VisitCount    int64                  `protobuf:"varint,6,opt,name=visit_count,json=visitCount,proto3" json:"visit_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortLink) Reset() {
	*x = ShortLink{}
	mi := &file_urlo_v1_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLink) ProtoMessage() {}

func (x *ShortLink) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLink.ProtoReflect.Descriptor instead.
func (*ShortLink) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{0}
}

func (x *ShortLink) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShortLink) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ShortLink) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShortLink) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ShortLink) GetVisitCount() int64 {
	if x != nil {
		return x.VisitCount
	}
	return 0
}

type ShortenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Long URL to shorten. Required.
	LongUrl string `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	// Optional custom code. If empty, the server generates one.
	CustomCode string `protobuf:"bytes,2,opt,name=custom_code,json=customCode,proto3" json:"custom_code,omitempty"`
	// Optional TTL in seconds. 0 means no expiration.
	TtlSeconds int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Optional length for the auto-generated code. 0 falls back to the
	// server's configured default. Must be within the server-supported
	// range (currently [6, 32]); ignored when custom_code is provided.
	CodeLength    int32 `protobuf:"varint,4,opt,name=code_length,json=codeLength,proto3" json:"code_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_urlo_v1_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ShortenRequest) GetCustomCode() string {
	if x != nil {
		return x.CustomCode
	}
	return ""
}

func (x *ShortenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *ShortenRequest) GetCodeLength() int32 {
	if x != nil {
		return x.CodeLength
	}
	return 0
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *ShortLink             `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_urlo_v1_url_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenResponse) GetLink() *ShortLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_urlo_v1_url_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *ShortLink             `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_urlo_v1_url_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveResponse) GetLink() *ShortLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_urlo_v1_url_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *ShortLink             `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_urlo_v1_url_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatsResponse) GetLink() *ShortLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_urlo_v1_url_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_urlo_v1_url_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{8}
}

// ClickEvent is a single recorded redirect.
type ClickEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned event id (e.g. redis stream id "1714521600123-0").
	Id   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Ts   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	// Hashed client IP (sha256(ip+salt) hex, first 16 bytes). Empty if disabled.
	IpHash  string `protobuf:"bytes,4,opt,name=ip_hash,json=ipHash,proto3" json:"ip_hash,omitempty"`
	Country string `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	City    string `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	// Full Referer header value.
	Referrer string `protobuf:"bytes,7,opt,name=referrer,proto3" json:"referrer,omitempty"`
	// Hostname extracted from referrer (e.g. "google.com").
	ReferrerHost string `protobuf:"bytes,8,opt,name=referrer_host,json=referrerHost,proto3" json:"referrer_host,omitempty"`
	UserAgent    string `protobuf:"bytes,9,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Browser      string `protobuf:"bytes,10,opt,name=browser,proto3" json:"browser,omitempty"`
	Os           string `protobuf:"bytes,11,opt,name=os,proto3" json:"os,omitempty"`
	// "desktop" | "mobile" | "tablet" | "bot" | "other".
	Device string `protobuf:"bytes,12,opt,name=device,proto3" json:"device,omitempty"`
	// First Accept-Language tag (e.g. "en-US").
	Lang          string `protobuf:"bytes,13,opt,name=lang,proto3" json:"lang,omitempty"`
	IsBot         bool   `protobuf:"varint,14,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickEvent) Reset() {
	*x = ClickEvent{}
	mi := &file_urlo_v1_url_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickEvent) ProtoMessage() {}

func (x *ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickEvent.ProtoReflect.Descriptor instead.
func (*ClickEvent) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{9}
}

func (x *ClickEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClickEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ClickEvent) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *ClickEvent) GetIpHash() string {
	if x != nil {
		return x.IpHash
	}
	return ""
}

func (x *ClickEvent) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ClickEvent) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ClickEvent) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *ClickEvent) GetReferrerHost() string {
	if x != nil {
		return x.ReferrerHost
	}
	return ""
}

func (x *ClickEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ClickEvent) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *ClickEvent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ClickEvent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ClickEvent) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ClickEvent) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

type ListClicksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Page size, default 50, max 500.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque cursor returned by previous response. Empty for first page.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClicksRequest) Reset() {
	*x = ListClicksRequest{}
	mi := &file_urlo_v1_url_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClicksRequest) ProtoMessage() {}

func (x *ListClicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClicksRequest.ProtoReflect.Descriptor instead.
func (*ListClicksRequest) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{10}
}

func (x *ListClicksRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ListClicksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListClicksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListClicksResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Events []*ClickEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Cursor for the next page; empty when no more pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClicksResponse) Reset() {
	*x = ListClicksResponse{}
	mi := &file_urlo_v1_url_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClicksResponse) ProtoMessage() {}

func (x *ListClicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlo_v1_url_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClicksResponse.ProtoReflect.Descriptor instead.
func (*ListClicksResponse) Descriptor() ([]byte, []int) {
	return file_urlo_v1_url_proto_rawDescGZIP(), []int{11}
}

func (x *ListClicksResponse) GetEvents() []*ClickEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListClicksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_urlo_v1_url_proto protoreflect.FileDescriptor

const file_urlo_v1_url_proto_rawDesc = "" +
	"\n" +
	"\x11urlo/v1/url.proto\x12\aurlo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x01\n" +
	"\tShortLink\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x19\n" +
	"\blong_url\x18\x02 \x01(\tR\alongUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1f\n" +
	"\vvisit_count\x18\x06 \x01(\x03R\n" +
	"visitCount\"\x8e\x01\n" +
	"\x0eShortenRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12\x1f\n" +
	"\vcustom_code\x18\x02 \x01(\tR\n" +
	"customCode\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12\x1f\n" +
	"\vcode_length\x18\x04 \x01(\x05R\n" +
	"codeLength\"9\n" +
	"\x0fShortenResponse\x12&\n" +
	"\x04link\x18\x01 \x01(\v2\x12.urlo.v1.ShortLinkR\x04link\"$\n" +
	"\x0eResolveRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"9\n" +
	"\x0fResolveResponse\x12&\n" +
	"\x04link\x18\x01 \x01(\v2\x12.urlo.v1.ShortLinkR\x04link\"%\n" +
	"\x0fGetStatsRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\":\n" +
	"\x10GetStatsResponse\x12&\n" +
	"\x04link\x18\x01 \x01(\v2\x12.urlo.v1.ShortLinkR\x04link\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x10\n" +
	"\x0eDeleteResponse\"\xf0\x02\n" +
	"\n" +
	"ClickEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x17\n" +
	"\aip_hash\x18\x04 \x01(\tR\x06ipHash\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x1a\n" +
	"\breferrer\x18\a \x01(\tR\breferrer\x12#\n" +
	"\rreferrer_host\x18\b \x01(\tR\freferrerHost\x12\x1d\n" +
	"\n" +
	"user_agent\x18\t \x01(\tR\tuserAgent\x12\x18\n" +
	"\abrowser\x18\n" +
	" \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\v \x01(\tR\x02os\x12\x16\n" +
	"\x06device\x18\f \x01(\tR\x06device\x12\x12\n" +
	"\x04lang\x18\r \x01(\tR\x04lang\x12\x15\n" +
	"\x06is_bot\x18\x0e \x01(\bR\x05isBot\"c\n" +
	"\x11ListClicksRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"i\n" +
	"\x12ListClicksResponse\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.urlo.v1.ClickEventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageTokenB2Z0github.com/kongken/urlo/pkg/proto/urlo/v1;urlov1b\x06proto3"

var (
	file_urlo_v1_url_proto_rawDescOnce sync.Once
	file_urlo_v1_url_proto_rawDescData []byte
)

func file_urlo_v1_url_proto_rawDescGZIP() []byte {
	file_urlo_v1_url_proto_rawDescOnce.Do(func() {
		file_urlo_v1_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_urlo_v1_url_proto_rawDesc), len(file_urlo_v1_url_proto_rawDesc)))
	})
	return file_urlo_v1_url_proto_rawDescData
}

var file_urlo_v1_url_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_urlo_v1_url_proto_goTypes = []any{
	(*ShortLink)(nil),             // 0: urlo.v1.ShortLink
	(*ShortenRequest)(nil),        // 1: urlo.v1.ShortenRequest
	(*ShortenResponse)(nil),       // 2: urlo.v1.ShortenResponse
	(*ResolveRequest)(nil),        // 3: urlo.v1.ResolveRequest
	(*ResolveResponse)(nil),       // 4: urlo.v1.ResolveResponse
	(*GetStatsRequest)(nil),       // 5: urlo.v1.GetStatsRequest
	(*GetStatsResponse)(nil),      // 6: urlo.v1.GetStatsResponse
	(*DeleteRequest)(nil),         // 7: urlo.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 8: urlo.v1.DeleteResponse
	(*ClickEvent)(nil),            // 9: urlo.v1.ClickEvent
	(*ListClicksRequest)(nil),     // 10: urlo.v1.ListClicksRequest
	(*ListClicksResponse)(nil),    // 11: urlo.v1.ListClicksResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_urlo_v1_url_proto_depIdxs = []int32{
	12, // 0: urlo.v1.ShortLink.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: urlo.v1.ShortLink.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 2: urlo.v1.ShortenResponse.link:type_name -> urlo.v1.ShortLink
	0,  // 3: urlo.v1.ResolveResponse.link:type_name -> urlo.v1.ShortLink
	0,  // 4: urlo.v1.GetStatsResponse.link:type_name -> urlo.v1.ShortLink
	12, // 5: urlo.v1.ClickEvent.ts:type_name -> google.protobuf.Timestamp
	9,  // 6: urlo.v1.ListClicksResponse.events:type_name -> urlo.v1.ClickEvent
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_urlo_v1_url_proto_init() }
func file_urlo_v1_url_proto_init() {
	if File_urlo_v1_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_urlo_v1_url_proto_rawDesc), len(file_urlo_v1_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_urlo_v1_url_proto_goTypes,
		DependencyIndexes: file_urlo_v1_url_proto_depIdxs,
		MessageInfos:      file_urlo_v1_url_proto_msgTypes,
	}.Build()
	File_urlo_v1_url_proto = out.File
	file_urlo_v1_url_proto_goTypes = nil
	file_urlo_v1_url_proto_depIdxs = nil
}
